language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
script:
  - npm run lint
  - npm run unit
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "Jean Yang"
  - git config user.email "bdlas321@gmail.com"
  - git add .
  - git commit -m "site updated"
  - git push --force https://$GH_TOKEN@github.com/erwaiyang/multiple-choice-game-vue.git gh-pages

branches:
  only:
    - master
